### ISSUE TITLE
add lsm dependency

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-dev-dependencies#5]
Inmanta modules that use lsm have `pytest-inmanta-lsm` as a dev dependency. This [used to be](https://github.com/inmanta/inmanta-dev-dependencies/blob/eb9e1c46eba76428f958582c93ec4fcdfc232dbb/pyproject.toml#L34) added as an extra dep but it was removed because dependabot could not access our private package repo. We might migrate to cloudsmith soon, once that's done the pytest-inmanta-lsm dependency could be added again, pointing dependabot to the cloudsmith repo.

**Comment by wouterdb** [comment]
@sanderr is this still relevant and is still still blocked?

**Comment by wouterdb** [comment]
This is most often not a dependency of our core development (more of demo's and solutions) (and not publicly available)
