### ISSUE TITLE
investigate auto-release pipeline

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-dev-dependencies#9]
It looks like v1.2.0 and v1.3.0 were released without changes in the pyproject.toml file. The Jenkinsfile was set up so that a release is triggered weekly, provided there were changes. The observation mentioned above indicates this condition does not work as expected. As a result, I expect a new version will be released every week, even if none of the package's dependencies have been bumped.

The root cause is that the version bump PR (which is applied on master but not on latest) updates the version in pyproject.toml as well. As a result there will always be a diff. The condition should be updated to take this into account.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-dev-dependencies/9?planning-poker) with ZenHub @andraskvr @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
